name: Build Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  review_pull_request_job:
    name: Run test cases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
#      - name: Setup JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Store cache
        uses: actions/checkout@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

# Don't run this anymore since we run Jacoco
#      - name: Run debug test
#        run: ./gradlew testDevDebugUnitTest --continue

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run lint
        run: ./gradlew lint

      - name: Run unit test and Jacoco Coverage
        run: ./gradlew :app:testDevDebugUnitTestCoverage

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundle and check environment versions
        run: |
          echo 'Install Bundle'
          bundle config path vendor/bundle
          bundle install
          echo 'Check environment setup versions'
          ruby --version
          gem --version
          bundler --version

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
        run: bundle exec danger